# Generated by Django 3.1.7 on 2021-03-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product List',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(null=True, unique=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer (User) Information',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_click_purchasing', models.BooleanField(default=False, null=True)),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('apartment_address', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, null=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Additional User Information',
            },
        ),
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('bannerTitle', models.CharField(default='Order Here', max_length=200)),
                ('BannerImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('title', models.CharField(max_length=100, null=True)),
                ('prodID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(null=True)),
                ('prodName', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('M', 'Meat'), ('ST', 'Starch'), ('F', 'Fruit'), ('ME', 'Meal'), ('D', 'Drink'), ('SN', 'Snacks')], max_length=2)),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateField(null=True)),
                ('product_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'Store Products',
            },
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(null=True)),
                ('order_type', models.CharField(choices=[('D', 'Delivery'), ('TO', 'Take Out'), ('IS', 'In Store')], default='', max_length=3)),
                ('ordered', models.BooleanField(default=False, null=True)),
                ('products', models.ManyToManyField(to='store.ProductList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Customer Orders',
            },
        ),
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
