# Generated by Django 3.1.7 on 2021-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
