# Generated by Django 3.1.7 on 2021-03-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210305_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepage',
            name='Banner_image',
        ),
        migrations.RemoveField(
            model_name='storepage',
            name='banner_title',
        ),
    ]
