# Generated by Django 3.1.7 on 2021-03-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210305_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.products'),
        ),
    ]
