# Generated by Django 3.1.7 on 2021-03-07 13:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210307_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepage',
            name='banner_title',
        ),
        migrations.AlterField(
            model_name='storepage',
            name='intro',
            field=wagtail.core.fields.StreamField([('intro_block', wagtail.core.blocks.StructBlock([('banner_title', wagtail.core.blocks.CharBlock(default='Welcome to the store', max_length=200)), ('intro', wagtail.core.blocks.TextBlock(blank=True, max_length=500))]))], blank=True, null=True),
        ),
    ]
