# Generated by Django 3.1.7 on 2021-03-06 04:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210305_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AlterField(
            model_name='storepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(help_text='Add Your Heading', template='store/heading_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add Your Image')), ('paragraph', wagtail.core.blocks.RichTextBlock(help_text='Add Your Paragraph'))], null=True),
        ),
    ]
