# Generated by Django 3.1.7 on 2021-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210305_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='Home Page!', max_length=100),
        ),
    ]
