# Generated by Django 3.1.7 on 2021-03-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='link',
            field=models.URLField(default='https://www.linkedin.com/in/nathan-brathwaite-80b7a1193/', max_length=100),
        ),
    ]
