# Generated by Django 3.1.7 on 2021-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_socialmediasettings_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
