# Generated by Django 3.1.7 on 2021-03-07 15:02

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('rich_text', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
